@Collectiv.FileServer_HostAddress = http://localhost:5062

GET {{Collectiv.FileServer_HostAddress}}/api/FileContainer/
Accept: application/json

###

POST {{Collectiv.FileServer_HostAddress}}/api/FileContainer/
Accept: application/json

###

DELETE {{Collectiv.FileServer_HostAddress}}/api/FileContainer/
Accept: application/json

###

GET {{Collectiv.FileServer_HostAddress}}/api/File/
Accept: application/json

###

POST {{Collectiv.FileServer_HostAddress}}/api/File/
Accept: application/json

###

DELETE {{Collectiv.FileServer_HostAddress}}/api/File/
Accept: application/json

###